experiment:
  name: tiny-imagenet-baseline

data:
  root: tiny-imagenet/tiny-imagenet-200
  resize_h: 224
  resize_w: 224
  norm_mean: [0.485, 0.456, 0.406]
  norm_std: [0.229, 0.224, 0.225]

model:
  name: CustomNet
  num_classes: 200

train:
  epochs: 10
  batch_size: 32
  lr: 0.001
  momentum: 0.9
  weight_decay: 0.0005
  num_workers: 8

eval:
  batch_size: 32
  num_workers: 4

device:
  use_cuda: true

wandb:
  enabled: true
  project: mldl-lab3
  entity: null
  mode: online  # online | offline | disabled
  run_name: null  # default: experiment.name

